config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "questions#index"

  resources :questions do
    resources :answers
  end
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    has_many :answers, dependent: :destroy
    
    validates :title, presence: true
    validates :content, presence: true, length: { minimum: 5 }
    validates :user_id, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def index
        @question = Question.all
        #@answers = Answer.where(question_id: @question.id).pluck(:id)
    end

    def show
        @question = Question.find_by(id: params[:id])
        @user = User.find_by(id: @question.user_id)
    end

    def new
      @question = Question.new()
    end

    def create
      @question = Question.new(question_params)
      if @question.save
        redirect_to question_path(@question.id)
      else
        render "new", status: :unprocessable_entity
      end
    end

    def edit
      @question = Question.find_by(id: params[:id])
    end

    def update
      @question = Question.find_by(id: params[:id])
      if @question.update(question_params)
        redirect_to @question
      else
        render "edit", status: :unprocessable_entity
      end
    end

    def destroy
      @question = Question.find_by(id: params[:id])
      if @question.destroy
        redirect_to root_path, status: :see_other
      else
        flash[:error] = "削除できませんでした" 
      end
    end

    private
    
    def question_params
      question = params.require(:question).permit(:title, :content)
      user = { "user_id" => current_user.id, "name" => current_user.name }
      return question.merge(user)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer_form.html.erb
  <!-- modal -->
  <div class="modal fade" id="answerModal" tabindex="-1" aria-labelledby="answerModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">回答を追加する</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <%= form_with model: [@question, @question.answers.build] do |form| %>
                    <div class="answer-errors">
                    </div>
                    <div class="answer-title">
                    </div>
                    <div class="answer-content">
                    <%= form.label "回答", class: "form-label" %><br>
                    <%= form.text_area :content, class: "form-control content-modal" %>
                    </div>
                    <div class="answer-submit">
                    <%# form.submit "回答を追加", class: "btn btn-outline-success" %>
                    </div>
            </div>

            <div class="modal-footer">
            <button type="button" class="btn btn-outline-warning" data-bs-dismiss="modal">キャンセル</button>
                    <%= form.submit "回答を追加", class: "btn btn-outline-success" %>
            </div>
                <% end %>
        </div>
    </div>
  </div>

app/views/questions/_form.html.erb
<div class="question-form">
  <%= form_with model: @question do |form| %>
    <% if @question.errors.any? %>
      <div>
        <ul>
          <% @question.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="question-title">
      <%= form.label "タイトル", class: "form-label" %><br>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="question-user">
      <%# form.label "ユーザー名", class: "form-label" %><br>
      <%# form.text_field :name, class: "form-control" %>
    </div>
    <div class="question-content">
      <%= form.label "内容", class: "form-label" %><br>
      <%= form.text_area :content, class: "form-control content" %>
    </div>
    <div class="question-submit">
      <%= form.submit "投稿", class: "btn btn-outline-success" %>
    </div>

  <% end %>
</div>
<div class="back-button">
  <%= link_to root_path do %>
    <button type="button" class="btn btn-outline-primary">戻る</button>
  <% end%>
<div>

app/views/questions/edit.html.erb
<h1 class="all-title">Edit</h1>
<%= render partial: "form" %>

app/views/questions/index.html.erb
<h1 class="all-title">みんなの質問</h1>
<div class="posts">
    <% @question.each do |q| %>
    <div class="card">
        <div class="card-body">
            <div class="card-title">
                <%= link_to q.title, question_path(q), data: { turbo: false } %>
            </div>
            <div class="card-subtitle">
                <i class="fa-regular fa-comment"></i><%= Answer.where(question_id: q.id).count %>
            </div>
        </div>
    </div>
    <% end %>
</div>
<%# link_to "edit", edit_question_path(q) %>
<%# link_to "delete", question_path(q), data:{ turbo_method: "delete", turbo_confirm: "Are you sure?" } %>

app/views/questions/new.html.erb
<h1 class="all-title">質問投稿</h1>
<%= render partial: "form" %>

app/views/questions/show.html.erb
<% if flash[:error]%>
  <div class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>
<div class="card">
  <div class="card-body">
    <p class="card-subtitle">
      <%# if @user != nil && @question.id == @user.id %>
      <% if @user != nil %>
        <%= @question.name %>
      <% else %>
        削除済みのユーザー
      <% end %>
    </p>
    <p class="card-text">
      <%= safe_join(@question.content.split("\n"), tag(:br)) %>
    </p>
    <% if user_signed_in? && @question.user_id == current_user.id %>
      <div class="answer-menu">
        <button type="button" class="btn btn-secondary" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa-solid fa-gear"></i>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to "質問を編集", edit_question_path(@question), class: "dropdown-item" %></li>
          <li><%= link_to "質問を削除", question_path(@question), data: { turbo_method: "delete", turbo_confirm: "本当に削除しますか?" }, class: "dropdown-item" %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? && @user != nil %>
  <!-- Button trigger modal -->
    <div class="answer-button">
      <button type="button" id="answer" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#answerModal">
      回答する
      </button>
    </div>
<% end %>

<% if @question.answers.length > 0 %>
  <div class="card">
    <h4 class="answers-count">
      回答(<%= @question.answers.count %>件)
    </h3>
    <% @question.answers.each do |answer| %>
        <div class="card-body answer">
          <p class="card-subtitle">
            <%= answer.name %>
          </p>
          <p class="card-text">
            <%= safe_join(answer.content.split("\n"), tag(:br)) %>
          </p>
          <% if user_signed_in? && answer.user_id == current_user.id %>
            <div class="answer-menu">
              <button type="button" class="btn btn-secondary" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-gear"></i>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "回答を削除", [answer.question, answer], data: { turbo_method: "delete", turbo_confirm: "本当に削除しますか?" }, class: "dropdown-item" %></li>
                <li><a class="dropdown-item" href="#">Menu item</a></li>
                <li><a class="dropdown-item" href="#">Menu item</a></li>
              </ul>
            </div>
          <% end %>
        </div>
    <% end %>
  </div>
<% end %>

<%= render partial: "answer_form" %>

<div class="back-button">
  <%= link_to root_path do %>
    <button type="button" class="btn btn-outline-primary">戻る</button>
  <% end%>
<div>