config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "questions#index"

  resources :questions do
    resources :answers
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>みんなの質問箱</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <% self_css_path = "/assets/"+controller.controller_path  %>
    <%= stylesheet_link_tag self_css_path, :media => "all" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffffff;">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link active" %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "新規投稿", new_question_path, class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= current_user.name %>
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><%= link_to "ユーザー編集", edit_user_registration_path, class: "dropdown-item" %></li>
                  <li><%= link_to "サインアウト", destroy_user_session_path, class: "dropdown-item" %></li>
                </ul>
              </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "サインアップ", new_user_registration_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>